name: Publish to GitHub Packages

on:
  workflow_dispatch:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  publish:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: macos-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        module:
          - almacen
          - login
          - users
          - habs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Configure Gradle
        run: |
          mkdir -p ~/.gradle
          echo "gpr.user=${{ github.actor }}" >> ~/.gradle/gradle.properties
          echo "gpr.key=${{ secrets.GITHUB_TOKEN }}" >> ~/.gradle/gradle.properties

      - name: Publish module ${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}-service-network-resources:publish :${{ matrix.module }}-service-network-model:publish
